FROM ubuntu:latest

ENV NONINTERACTIVE=1
RUN apt-get update && \
    apt-get install -y curl git && \
    rm -rf /var/lib/apt/lists/*
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && \
  (/home/linuxbrew/.linuxbrew/bin/brew install curl git gcc man-db || :) && \
  mv /home/linuxbrew /opt/
