apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "boombox.fullname" . }}-config
  labels:
    {{- include "boombox.labels" . | nindent 4 }}
data:
  {{- if .Values.config.listen }}
  BOOMBOX_LISTEN: {{ .Values.config.listen }}
  {{- end }}
  {{- if .Values.config.namespace }}
  BOOMBOX_NAMESPACE: {{ .Values.config.namespace }}
  {{- end }}
  {{- if .Values.config.hostKeyPath }}
  BOOMBOX_HOST_KEY_PATH: {{ .Values.config.hostKeyPath }}
  {{- end }}
  {{- if .Values.config.containerImage }}
  BOOMBOX_CONTAINER_IMAGE: {{ .Values.config.containerImage }}
  {{- end }}
  {{- if .Values.config.pvcSize }}
  BOOMBOX_PVC_SIZE: {{ .Values.config.pvcSize }}
  {{- end }}
  {{- if .Values.config.logLevel }}
  BOOMBOX_LOG_LEVEL: {{ .Values.config.logLevel }}
  {{- end }}
