{{- if and .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "boombox.labels" . | nindent 4 }}
  name: {{ include "boombox.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "boombox.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "boombox.fullname" . }}
{{- end }}
