{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "boombox.labels" . | nindent 4 }}
  name: {{ include "boombox.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - pods
      - pods/log
      - pods/exec
    verbs:
      - create
      - delete
      - get
      - watch
{{- end }}
