{{- if .Values.secrets.hostKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boombox.fullname" . }}-host-key
  labels:
    {{- include "boombox.labels" . | nindent 4 }}
stringData:
  boombox_ed25519: {{ .Values.secrets.hostKey | quote }}
{{- end }}
